TrossenRobotics/trossen_arm

docs/changelog.rst
docs/index.rst

looking a bit bland at the moment, but don't have other ideas that can fit in

added changelog

---

CMakeLists.txt
include/libtrossen_arm/trossen_arm.hpp
include/libtrossen_arm/trossen_arm_config.hpp
package.xml

Deploy v1.7.2

---

CMakeLists.txt
include/libtrossen_arm/trossen_arm.hpp
include/libtrossen_arm/trossen_arm_config.hpp
package.xml

Deploy v1.7.3

---

docs/getting_started/configuration.rst

changed from 2.0 to 5.0
added ranges for applicable configurations

changed continuity factor default and added ranges

---

docs/getting_started/demo_scripts.rst

added the demo to the demo scripts page

added demo on error recovery

---

docs/tutorials/lerobot.rst
docs/tutorials/lerobot/configuration.rst
docs/tutorials/lerobot/record_episode.rst
docs/tutorials/lerobot/replay.rst
docs/tutorials/lerobot/setup.rst
docs/tutorials/lerobot/teleoperation.rst
docs/tutorials/lerobot/train_and_evaluate.rst
docs/tutorials/lerobot/visualize.rst

1. Added Documentation for using Trossen AI Statioanry, Mobile and Solo.
2. Used tabs to efficiently manage all configurations under single page.

Update Docs for All Trossen AI Kits

---

docs/getting_started/software_setup.rst

Fixed the name of the repository in 'software_setup.rst'

Fixed repository name

---

docs/getting_started/hardware_setup.rst

This PR adds the Mobile AI Kit assembly guide to the hardware setup docs.

Add Mobile AI Kit Assembly Video

---

docs/_static/tr_style.css
docs/getting_started/software_setup.rst

This PR adds a table describing the compatible operating systems and architectures.

Add platform compatibility table

---

docs/getting_started/hardware_setup.rst

This PR adds the Stationary AI Kit assembly guide to the hardware setup docs.

Add Stationary AI Kit Assembly Video

---

docs/specifications.rst

- added classic and modified dh parameters
- added a justification on the effort limits

Add dh parameters

---

docs/conf.py
docs/requirements.txt
docs/tutorials.rst
docs/tutorials/trossen_arm_mujoco.rst

This PR adds usage and troubleshooting documentation for using MuJoCo with Trossen AI Arms.

[documentation]: adds usage documentation for MuJoCo

---

docs/tutorials/lerobot.rst
docs/tutorials/lerobot/changelog.rst
docs/tutorials/lerobot/configuration.rst
docs/tutorials/lerobot/record_episode.rst
docs/tutorials/lerobot/replay.rst
docs/tutorials/lerobot/teleoperation.rst
docs/tutorials/lerobot/train_and_evaluate.rst

This PR adds the following
1. Information on how to configure `Open CV` for cameras
2. Change Log about dataset version. 
3. How to use dataset conversion scripts.

[documentation]: document latest updates and features from `Interbotix/lerobot`

---

docs/getting_started/software_setup.rst

This PR adds boost dependency installation to the software setup guide.

Update dependency installation according to 1.8

---

CMakeLists.txt
demos/cpp/mixed_interpolation_space.cpp
demos/python/mixed_interpolation_space.py
package.xml

Deploy v1.8.1

---

CMakeLists.txt
demos/cpp/configuration_in_yaml.cpp
demos/cpp/configure_cleanup.cpp
demos/cpp/default_configurations_wxai_v0.yaml
demos/cpp/gripper_torque.cpp
demos/cpp/mixed_interpolation_space.cpp
demos/cpp/set_joint_limits.cpp
demos/python/default_configurations_wxai_v0.yaml
demos/python/gripper_torque.py
demos/python/mixed_interpolation_space.py
demos/python/set_joint_limits.py
include/libtrossen_arm/trossen_arm.hpp
package.xml

Deploy v1.8.2

---

docs/changelog.rst

covered
- add vxai
- take out gripper
- prettify udp warning

document: add changelog for 183

---

CMakeLists.txt
demos/cpp/default_configurations_vxai_v0.yaml
demos/python/default_configurations_vxai_v0.yaml
include/libtrossen_arm/trossen_arm.hpp
include/libtrossen_arm/trossen_arm_type.hpp
package.xml

Deploy v1.8.3

---

docs/specifications.rst

This PR fixes the kinematic properties of the WidowX AI based on the changes in https://github.com/TrossenRobotics/trossen_arm_description/pull/8

Update DH parameters with updated tool frame

---

docs/changelog.rst
docs/getting_started/demo_scripts.rst

This PR adds the changelogs for:
* Arm Controller firmware v1.8.4
* Trossen Arm Driver v1.8.4
* Trossen Arm Driver v1.8.5
* Updates the name and link of the error recovery demo
* Adds the joint characteristics fine tuning script

Changelog for v1.8.4, v1.8.5

---

docs/getting_started/hardware_setup.rst

This PR updates the WidowX AI assembly guides.

Update WidowX AI Assembly Guides

---

docs/community.rst
docs/index.rst

Adds a stub community page to the documentation.

Add community page

---

CMakeLists.txt
demos/cpp/gravity_compensation_partial.cpp
demos/python/gravity_compensation_partial.py
package.xml

Deploy v1.8.6

---

docs/changelog.rst
docs/getting_started/demo_scripts.rst

- used section for name and subsection for version since patch changes are not required to match
- added changelog for driver 1.8.6

Documentation: update changelog for driver 1.8.6

---

docs/tutorials/trossen_data_collection_ui.rst

Updating the UI documentation to include the following
1. Explain the Task Config YAML
2. Explain the Robot Config YAML
3. Make OpenCV as default (Or explicitly ask to use opencv for good results)
4. Troubleshooting (disable ui, disable cameras, use opencv, increase min time to move if necessary)

Update Documentation for Trossen Data Collection UI

---

CMakeLists.txt
demos/cpp/configuration_in_yaml.cpp
demos/cpp/configure_cleanup.cpp
demos/python/configuration_in_yaml.py
demos/python/configure_cleanup.py
include/libtrossen_arm/trossen_arm.hpp
include/libtrossen_arm/trossen_arm_type.hpp
package.xml

Deploy v1.9.0

---

docs/getting_started/software_setup.rst
docs/index.rst
docs/tutorials/lerobot/configuration.rst
docs/tutorials/trossen_data_collection_ui.rst

This PR does the following:
* Adds an explicit Arm Network Setup guide for the case where users may want to change the IP address
* Minor cleanup and clarification
* Corrected configuration behavior through firmware flashing

[docs] Arm controller network setup, firmware flashing correction, cleanup
